### ISSUE TITLE
Add colours support for the logs

### ISSUE THREAD

**Issue by studcroc** [hvg2416/boxer#4]
It will be good if the boxer can log out the messages with a variety of different colors.

**Comment by Akash82228** [comment]
Please assign this issue to me i can resolve this issue

**Comment by studcroc** [comment]
@Akash82228 okay you can proceed.
Just to give some idea, I already added one file named **colors.dart** where we can store all color codes as constants. So please append to that file if you need to.

Go ahead. I am assigning this issue to you. All the best.

**Comment by Akash82228** [comment]
@hvg2416  can you briefly explain what changes you need in the repo. because i have some confusion

**Comment by Akash82228** [comment]
i made many flutter apps it will be perfect if i know exactly what i have to do.

**Comment by studcroc** [comment]
@Akash82228 you can refer to the screenshot in the readme. There you will notice that all the logs are printed in one color & that's fine for normal logs. But in case of error messages or if the user explicitly wants to print logs in some other color e.g red, blue, etc. So if we have that feature to print logs in multiple colors, that will be great.

**Comment by studcroc** [comment]
@Akash82228 anyways if you are in doubt, I suggest to look for other contributions 😄 because this issue most probably I will resolve very soon.

**Comment by Akash82228** [comment]
@hvg2416  no problem but it's interesting what this repo is all about never think about changing the log colour
🤯

**Comment by phan-dev** [comment]
@hvg2416 
This issue was resolved by #5 , right?

**Comment by studcroc** [comment]
@phan-dev yeah sorry for the miscommunication.

**Comment by phan-dev** [comment]
@hvg2416 
Great feature!!!
I think it's missed the update of example.
Do you want me to update it?

**Comment by studcroc** [comment]
@phan-dev sorry to inform you but I feel I am almost done with the changes & will add them soon. 
Anyways thank you for showing interest.
